/**
 * Manifest-driven responsive image utilities.
 *
 * Loads /images/_manifest.json generated by scripts/optimize_images.py
 * and provides helpers to select the best variant for a given display size.
 */

export type ImageVariant = {
  src: string;
  width: number;
  height: number;
  format?: string; // e.g., 'webp', 'avif'
};

export type ImageManifest = Record<string, {
  webp?: ImageVariant[];
  avif?: ImageVariant[];
}>;

type NormalizedManifest = Record<string, ImageVariant[]>; // key: original web path '/images/..'

let manifestPromise: Promise<NormalizedManifest> | null = null;

function toWebPath(p: string): string {
  if (!p) return p;
  // Normalize backslashes
  const normalized = p.replace(/\\/g, '/');
  const marker = '/images/';
  const idx = normalized.indexOf(marker);
  if (idx >= 0) return normalized.slice(idx);
  // Fallback: use just the filename under /images
  const base = normalized.split('/').pop() || normalized;
  return base.startsWith('/images/') ? base : `/images/${base}`;
}

async function loadManifest(): Promise<NormalizedManifest> {
  if (manifestPromise) return manifestPromise;
  manifestPromise = (async () => {
    try {
      const res = await fetch('/images/_manifest.json', { cache: 'force-cache' });
      if (!res.ok) throw new Error(`Manifest HTTP ${res.status}`);
      const raw = (await res.json()) as ImageManifest;
      const map: NormalizedManifest = {};
      for (const [rawKey, entry] of Object.entries(raw)) {
        const key = toWebPath(rawKey);
        const all: ImageVariant[] = [];
        const pushList = (list?: ImageVariant[], format?: string) => {
          if (!list) return;
          for (const v of list) {
            all.push({ src: toWebPath(v.src), width: v.width, height: v.height, format });
          }
        };
        pushList(entry.webp, 'webp');
        // Prefer AVIF first in future if present; keep order stable but we'll sort later
        pushList(entry.avif, 'avif');
        // Deduplicate by width+format
        const dedup = new Map<string, ImageVariant>();
        for (const v of all) {
          dedup.set(`${v.format || 'webp'}:${v.width}`, v);
        }
        const list = Array.from(dedup.values()).sort((a, b) => a.width - b.width);
        if (list.length) map[key] = list;
      }
      return map;
    } catch (e) {
      console.warn('[imageManifest] Failed to load manifest:', e);
      return {} as NormalizedManifest;
    }
  })();
  return manifestPromise;
}

/**
 * Select the best variant given desired CSS pixels and device pixel ratio.
 * If no variants exist, returns the original URL.
 */
export async function getBestImageUrl(originalUrl: string, desiredCssWidth: number, dpr = 1): Promise<string> {
  const webPath = toWebPath(originalUrl);
  const manifest = await loadManifest();
  const variants = manifest[webPath];
  if (!variants || variants.length === 0) return webPath;
  const target = Math.max(1, Math.round(desiredCssWidth * Math.max(1, Math.min(2.5, dpr))));
  // Pick the smallest variant >= target, else the largest available
  const candidate = variants.find(v => v.width >= target) ?? variants[variants.length - 1];
  return candidate.src;
}

/** Build a srcset string from manifest variants. Fallback to empty string when missing. */
export async function getSrcSet(originalUrl: string): Promise<string> {
  const webPath = toWebPath(originalUrl);
  const manifest = await loadManifest();
  const variants = manifest[webPath];
  if (!variants || variants.length === 0) return '';
  // Prefer avif if present by listing it first with type via <source>. For img srcset, just widths.
  const uniqueByWidth = new Map<number, ImageVariant>();
  for (const v of variants) {
    // keep the first occurrence for a width (likely avif first in future)
    if (!uniqueByWidth.has(v.width)) uniqueByWidth.set(v.width, v);
  }
  const items = Array.from(uniqueByWidth.values()).sort((a, b) => a.width - b.width);
  return items.map(v => `${v.src} ${v.width}w`).join(', ');
}

/**
 * Convenience: compute a best-effort immediate URL synchronously by guessing variant naming when manifest isn't loaded yet.
 * Useful as initial src placeholder. It tries to downshift to a mid-size (e.g., 640w) if that file exists in the same folder.
 */
export function guessInitialUrl(originalUrl: string, preferredWidth = 640): string {
  const webPath = toWebPath(originalUrl);
  const idx = webPath.lastIndexOf('.');
  if (idx <= 0) return webPath;
  const base = webPath.slice(0, idx);
  const ext = webPath.slice(idx);
  // Our generator names like name-w{width}.webp in /images (some variants were written at root /images)
  const fileName = base.split('/').pop() || base;
  return `/images/${fileName}-w${preferredWidth}.webp`;
}

/**
 * For background images: select best URL based on a given element width.
 */
export async function selectBackgroundUrl(originalUrl: string, elementWidth: number, dpr = 1): Promise<string> {
  return getBestImageUrl(originalUrl, elementWidth, dpr);
}

/**
 * Public API: preload manifest early, e.g., in app bootstrap.
 */
export function warmImageManifest(): void {
  void loadManifest();
}
